FROM python:3.10
WORKDIR /code
RUN apt-get -y update \
    && apt-get install -y python3-pip python3-dev libpq-dev postgresql postgresql-contrib netcat \
    && apt-get -y clean gettext \
RUN pip install --upgrade pip setuptools wheel
ADD ./requirements.txt /code/requirements.txt
RUN pip install -r requirements.txt
